// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-menu-inline-collapsed': string;
  'ant-menu-item': string;
  'ant-menu-item-group': string;
  'ant-menu-item-group-list': string;
  'ant-menu-submenu': string;
  'ant-menu-submenu-title': string;
  'drawer': string;
  'drawer-content': string;
  'icon': string;
  'ligth': string;
  'logo': string;
  'sider': string;
  'sider-menu': string;
  'sider-menu-item-img': string;
}
export const cssExports: CssExports;
export default cssExports;
